# Generated by Django 5.0.6 on 2024-06-11 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('source_id', models.IntegerField(unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Character',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('air_date', models.CharField(max_length=100)),
                ('episode', models.CharField(max_length=100)),
                ('source_id', models.IntegerField(unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('characters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_characters', to='app.character')),
            ],
            options={
                'verbose_name': 'Episode',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_in_episode', to='app.episode'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('source_id', models.IntegerField(unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('residents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_locations', to='app.character')),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_characters', to='app.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_characters', to='app.location'),
        ),
    ]
