# Generated by Django 5.0.6 on 2024-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='location',
            name='residents',
        ),
        migrations.AddField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(related_name='episode_characters', to='app.character'),
        ),
        migrations.AddField(
            model_name='location',
            name='residents',
            field=models.ManyToManyField(related_name='residents_locations', to='app.character'),
        ),
    ]
